import crneoci from "../../assets/crneoci.jpg";
import kajlo from "../../assets/kajlo.jpg";
import samojedanje from "../../assets/samojedanje.jpg";
import bestof from "../../assets/bestof.jpg";
import istinom from "../../assets/istinom.jpg";
// crne oci
import {
  odlazimDalekoText,
  strahMeJeText,
  crneOciText,
  onSeNeceVratitiText,
  nijeLjubavText,
  akoSeNekadText,
  zivjetiText,
  tiUMislimaText,
  mnogeCeMajkeText,
} from "./crneOciAPI/crneOciText.js";
import {
  odlazimDalekoYT,
  strahMeJeYT,
  crneOciYT,
  onSeNeceVratitiYT,
  nijeLjubavYT,
  akoSeNekadYT,
  zivjetiYT,
  tiUMislimaYT,
  mnogeCeMajkeYT,
  odlazimDalekoSP,
  strahMeJeSP,
  crneOciSP,
  onSeNeceVratitiSP,
  nijeLjubavSP,
  akoSeNekadSP,
  zivjetiSP,
  tiUMislimaSP,
  mnogeCeMajkeSP,
} from "./crneOciAPI/crneOciPaths.js";
// kajloStara
import {
  jedanDanYT,
  kraljicaYT,
  mahalaYT,
  iSadKadBiYT,
  tiTrebasLjubavYT,
  idiZenoYT,
  hajdeJadnaYT,
  trunkaYT,
  opsesijaYT,
  ostaniTuYT,
  kajloStaraYT,
  jedanDanSP,
  kraljicaSP,
  mahalaSP,
  iSadKadBiSP,
  tiTrebasLjubavSP,
  idiZenoSP,
  hajdeJadnaSP,
  trunkaSP,
  opsesijaSP,
  ostaniTuSP,
  kajloStaraSP,
} from "./kajloStaraAPI/kajloStaraPaths.js";
import {
  jedanDanText,
  kraljicaText,
  mahalaText,
  iSadKadBiText,
  tiTrebasLjubavText,
  idiZenoText,
  hajdeJadnaText,
  trunkaText,
  opsesijaText,
  ostaniTuText,
  kajloStaraText,
} from "./kajloStaraAPI/kajloStaraText.js";

const AlbumData = {
  crneoci: {
    albumName: "Crne Oči",
    img: crneoci,
    songs: [
      "Odlazim daleko",
      "Strah me je",
      "Crne oči",
      "On se neće vratiti",
      "Nije ljubav",
      "Ako se nekad",
      "Živjeti",
      "Ti u mislima",
      "Mnoge će majke",
    ],
    ytLinks: [
      odlazimDalekoYT,
      strahMeJeYT,
      crneOciYT,
      onSeNeceVratitiYT,
      nijeLjubavYT,
      akoSeNekadYT,
      zivjetiYT,
      tiUMislimaYT,
      mnogeCeMajkeYT,
    ],
    spLinks: [
      odlazimDalekoSP,
      strahMeJeSP,
      crneOciSP,
      onSeNeceVratitiSP,
      nijeLjubavSP,
      akoSeNekadSP,
      zivjetiSP,
      tiUMislimaSP,
      mnogeCeMajkeSP,
    ],
    tekst: [
      odlazimDalekoText,
      strahMeJeText,
      crneOciText,
      onSeNeceVratitiText,
      nijeLjubavText,
      akoSeNekadText,
      zivjetiText,
      tiUMislimaText,
      mnogeCeMajkeText,
    ],
    albumLink: "https://songwhip.com/macbeth/crne-oci",
  },
  kajlo: {
    albumName: "Kajlo Stara",
    img: kajlo,
    songs: [
      "Jedan dan",
      "Kraljica",
      "Mahala",
      "I sad' kad' bi'",
      "Ti trebaš ljubav",
      "Idi ženo",
      "Hajde jadna",
      "Trunka",
      "Opsesija",
      "Ostani tu",
      "Kajlo stara",
    ],
    ytLinks: [
      jedanDanYT,
      kraljicaYT,
      mahalaYT,
      iSadKadBiYT,
      tiTrebasLjubavYT,
      idiZenoYT,
      hajdeJadnaYT,
      trunkaYT,
      opsesijaYT,
      ostaniTuYT,
      kajloStaraYT,
    ],
    spLinks: [
      jedanDanSP,
      kraljicaSP,
      mahalaSP,
      iSadKadBiSP,
      tiTrebasLjubavSP,
      idiZenoSP,
      hajdeJadnaSP,
      trunkaSP,
      opsesijaSP,
      ostaniTuSP,
      kajloStaraSP,
    ],
    tekst: [
      jedanDanText,
      kraljicaText,
      mahalaText,
      iSadKadBiText,
      tiTrebasLjubavText,
      idiZenoText,
      hajdeJadnaText,
      trunkaText,
      opsesijaText,
      ostaniTuText,
      kajloStaraText,
    ],
    albumLink: "https://songwhip.com/macbeth/kajlostara",
  },
  samojedanje: {
    albumName: "Samo jedan Je",
    img: samojedanje,
    // songs: 8,
    albumLink: "https://songwhip.com/macbeth/samo-jedan-je",
  },
  bestof: {
    albumName: "Best Of",
    img: bestof,
    // songs: 9,
    albumLink: "https://songwhip.com/macbeth/istinom",
  },
  istinom: {
    albumName: "Istinom",
    img: istinom,
    // songs: 9,
    albumLink: "https://songwhip.com/macbeth/istinom",
  },
};
export default AlbumData;
